# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReleaseManager' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReleaseManager

  target 'ReleaseManagerTests' do
    inherit! :search_paths
    pod 'OCMock', '~> 3.4'
  end

  target 'ReleaseManagerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
